import type {
  Patient,
  Demographics,
  VitalSigns,
  HistoryPresentIllness,
  PastMedicalHistory,
  MedicationHistory,
  AllergyHistory,
  Case,
  Test,
  Medicine,
  Diagnosis,
  Treatment,
} from "~/types";

// Mock Demographics
const demographics: Demographics[] = [
  {
    _id: "demo1",
    patient_id: "CVD001",
    first_name: "张",
    last_name: "伟明",
    date_of_birth: new Date("1965-03-15"),
    gender: "male",
    phone: "13812345678",
    email: "zhang.weiming@email.com",
    address: "上海市浦东新区张江高科技园区",
    emergency_contact_name: "张丽华 (妻子)",
    emergency_contact_phone: "13987654321",
    insurance_info: "上海市城镇职工基本医疗保险",
    created_at: new Date("2024-01-01"),
    updated_at: new Date("2024-01-15"),
  },
  {
    _id: "demo2",
    patient_id: "CVD002",
    first_name: "李",
    last_name: "美玲",
    date_of_birth: new Date("1972-08-22"),
    gender: "female",
    phone: "13698765432",
    email: "li.meiling@email.com",
    address: "北京市朝阳区CBD中心区",
    emergency_contact_name: "李强 (丈夫)",
    emergency_contact_phone: "13567890123",
    insurance_info: "北京市城镇职工基本医疗保险",
    created_at: new Date("2024-01-02"),
    updated_at: new Date("2024-01-16"),
  },
  {
    _id: "demo3",
    patient_id: "CVD003",
    first_name: "王",
    last_name: "建国",
    date_of_birth: new Date("1958-12-08"),
    gender: "male",
    phone: "13445678901",
    email: "wang.jianguo@email.com",
    address: "广州市天河区珠江新城",
    emergency_contact_name: "王秀英 (妻子)",
    emergency_contact_phone: "13234567890",
    insurance_info: "广州市城镇职工基本医疗保险",
    created_at: new Date("2024-01-03"),
    updated_at: new Date("2024-01-17"),
  },
];

// Mock Vital Signs
const vitalSigns: VitalSigns[] = [
  {
    _id: "vital1",
    patient_id: "CVD001",
    temperature: 36.8,
    blood_pressure_systolic: 145,
    blood_pressure_diastolic: 92,
    heart_rate: 88,
    respiratory_rate: 18,
    oxygen_saturation: 97.5,
    height: 175,
    weight: 82,
    bmi: 26.8,
    pain_scale: 3,
    measurement_date: new Date("2024-01-15T09:30:00"),
    notes: "轻度高血压，需要监测",
    created_at: new Date("2024-01-15T09:30:00"),
    updated_at: new Date("2024-01-15T09:30:00"),
  },
  {
    _id: "vital2",
    patient_id: "CVD002",
    temperature: 37.1,
    blood_pressure_systolic: 160,
    blood_pressure_diastolic: 95,
    heart_rate: 95,
    respiratory_rate: 20,
    oxygen_saturation: 96.8,
    height: 162,
    weight: 68,
    bmi: 25.9,
    pain_scale: 7,
    measurement_date: new Date("2024-01-16T14:15:00"),
    notes: "胸痛伴高血压，需要紧急评估",
    created_at: new Date("2024-01-16T14:15:00"),
    updated_at: new Date("2024-01-16T14:15:00"),
  },
  {
    _id: "vital3",
    patient_id: "CVD003",
    temperature: 36.5,
    blood_pressure_systolic: 180,
    blood_pressure_diastolic: 110,
    heart_rate: 102,
    respiratory_rate: 22,
    oxygen_saturation: 94.5,
    height: 170,
    weight: 85,
    bmi: 29.4,
    pain_scale: 5,
    measurement_date: new Date("2024-01-17T11:00:00"),
    notes: "严重高血压，心率不齐",
    created_at: new Date("2024-01-17T11:00:00"),
    updated_at: new Date("2024-01-17T11:00:00"),
  },
];

// Mock History of Present Illness
const historyPresentIllness: HistoryPresentIllness[] = [
  {
    _id: "hpi1",
    patient_id: "CVD001",
    chief_complaint: "胸闷气短2周",
    history_of_present_illness:
      "患者2周前开始出现胸闷气短，尤其在活动时加重，休息后有所缓解。无明显胸痛，偶有头晕。",
    onset: "gradual",
    duration: "2 weeks",
    severity: 4,
    quality: "压迫性",
    radiation: "无",
    associated_symptoms: ["头晕", "乏力"],
    alleviating_factors: ["休息"],
    aggravating_factors: ["活动", "情绪激动"],
    previous_episodes: false,
    notes: "患者有高血压家族史",
    created_at: new Date("2024-01-15"),
    updated_at: new Date("2024-01-15"),
  },
  {
    _id: "hpi2",
    patient_id: "CVD002",
    chief_complaint: "急性胸痛4小时",
    history_of_present_illness:
      "患者4小时前突然出现剧烈胸痛，呈压榨性，向左臂放射，伴恶心呕吐，大汗淋漓。",
    onset: "sudden",
    duration: "4 hours",
    severity: 9,
    quality: "压榨性",
    radiation: "左臂",
    associated_symptoms: ["恶心", "呕吐", "大汗"],
    alleviating_factors: ["含服硝酸甘油稍缓解"],
    aggravating_factors: ["活动"],
    previous_episodes: false,
    notes: "高度怀疑急性心肌梗死",
    created_at: new Date("2024-01-16"),
    updated_at: new Date("2024-01-16"),
  },
  {
    _id: "hpi3",
    patient_id: "CVD003",
    chief_complaint: "心慌气短1个月",
    history_of_present_illness:
      "患者1个月来反复出现心慌气短，夜间平卧时加重，需要坐起才能缓解，伴下肢水肿。",
    onset: "gradual",
    duration: "1 month",
    severity: 6,
    quality: "心慌",
    radiation: "无",
    associated_symptoms: ["下肢水肿", "夜间端坐呼吸"],
    alleviating_factors: ["坐位", "利尿"],
    aggravating_factors: ["平卧", "活动"],
    previous_episodes: true,
    notes: "既往有心肌梗死病史",
    created_at: new Date("2024-01-17"),
    updated_at: new Date("2024-01-17"),
  },
];

// Mock Cases
const cases: Case[] = [
  {
    _id: "case1",
    patient_id: "CVD001",
    case_number: "CVD001-20240115",
    soap: "主观：胸闷气短2周\n客观：BP 145/92, HR 88, 心电图示左室肥厚\n评估：高血压病，疑似冠心病\n计划：完善冠脉造影，调整降压药物",
    case_date: new Date("2024-01-15"),
    transcriptions:
      "患者张伟明，59岁男性，主诉胸闷气短2周。患者诉2周前开始出现胸闷气短，活动时加重，休息后缓解。查体：血压145/92mmHg，心率88次/分，心界不大，心律齐，未闻及杂音。心电图示左室肥厚改变。",
    status: "in_progress",
    notes: "需要完善冠脉检查",
    created_at: new Date("2024-01-15"),
    updated_at: new Date("2024-01-15"),
  },
  {
    _id: "case2",
    patient_id: "CVD002",
    case_number: "CVD002-20240116",
    soap: "主观：急性胸痛4小时\n客观：BP 160/95, HR 95, 心电图示ST段抬高\n评估：急性ST段抬高型心肌梗死\n计划：急诊PCI，抗血小板聚集治疗",
    case_date: new Date("2024-01-16"),
    transcriptions:
      "患者李美玲，52岁女性，急诊就诊，主诉急性胸痛4小时。患者4小时前突然出现剧烈胸痛，呈压榨性，向左臂放射，伴恶心呕吐。查体：血压160/95mmHg，心率95次/分，心音低钝。心电图示V1-V6导联ST段抬高。",
    status: "open",
    notes: "急性心肌梗死，需要紧急介入治疗",
    created_at: new Date("2024-01-16"),
    updated_at: new Date("2024-01-16"),
  },
  {
    _id: "case3",
    patient_id: "CVD003",
    case_number: "CVD003-20240117",
    soap: "主观：心慌气短1个月\n客观：BP 180/110, HR 102不齐, 双下肢水肿\n评估：心力衰竭，房颤\n计划：利尿，抗凝，心律转复",
    case_date: new Date("2024-01-17"),
    transcriptions:
      "患者王建国，66岁男性，主诉心慌气短1个月。患者1个月来反复心慌气短，夜间端坐呼吸，双下肢水肿。查体：血压180/110mmHg，心率102次/分绝对不齐，心界扩大，可闻及收缩期杂音，双下肢凹陷性水肿。",
    status: "in_progress",
    notes: "心力衰竭合并房颤",
    created_at: new Date("2024-01-17"),
    updated_at: new Date("2024-01-17"),
  },
];

// Mock Tests
const tests: Test[] = [
  {
    _id: "test1",
    case_id: "case1",
    patient_id: "CVD001",
    test_name: "冠状动脉造影",
    test_date: new Date("2024-01-15"),
    notes: "评估冠脉狭窄程度",
    results: ["左前降支近端50%狭窄", "回旋支中段30%狭窄", "右冠状动脉正常"],
    created_at: new Date("2024-01-15"),
    updated_at: new Date("2024-01-15"),
  },
  {
    _id: "test2",
    case_id: "case2",
    patient_id: "CVD002",
    test_name: "心肌酶谱",
    test_date: new Date("2024-01-16"),
    notes: "评估心肌损伤",
    results: [
      "CK-MB: 258 ng/mL (正常<6.3)",
      "Troponin I: 45.2 ng/mL (正常<0.04)",
      "CK: 2890 U/L (正常<190)",
    ],
    created_at: new Date("2024-01-16"),
    updated_at: new Date("2024-01-16"),
  },
  {
    _id: "test3",
    case_id: "case3",
    patient_id: "CVD003",
    test_name: "超声心动图",
    test_date: new Date("2024-01-17"),
    notes: "评估心脏结构和功能",
    results: [
      "左室射血分数: 35%",
      "左房扩大: 4.8cm",
      "二尖瓣轻度关闭不全",
      "室壁运动异常",
    ],
    created_at: new Date("2024-01-17"),
    updated_at: new Date("2024-01-17"),
  },
];

// Mock Diagnoses
const diagnoses: Diagnosis[] = [
  {
    _id: "diag1",
    case_id: "case1",
    patient_id: "CVD001",
    diagnosis_name: "冠心病 不稳定性心绞痛",
    diagnosis_date: new Date("2024-01-15"),
    status: "active",
    probability: 85,
    notes: "基于临床症状和冠脉造影结果",
    follow_up: "3个月后复查冠脉造影",
    additional_info: "需要药物治疗和生活方式干预",
    created_at: new Date("2024-01-15"),
    updated_at: new Date("2024-01-15"),
  },
  {
    _id: "diag2",
    case_id: "case2",
    patient_id: "CVD002",
    diagnosis_name: "急性ST段抬高型心肌梗死",
    diagnosis_date: new Date("2024-01-16"),
    status: "active",
    probability: 95,
    notes: "典型临床表现，心电图和心肌酶证实",
    follow_up: "1周后复查心功能",
    additional_info: "需要急诊PCI和标准化药物治疗",
    created_at: new Date("2024-01-16"),
    updated_at: new Date("2024-01-16"),
  },
  {
    _id: "diag3",
    case_id: "case3",
    patient_id: "CVD003",
    diagnosis_name: "慢性心力衰竭 心房颤动",
    diagnosis_date: new Date("2024-01-17"),
    status: "active",
    probability: 90,
    notes: "临床症状明确，超声心动图支持",
    follow_up: "2周后复查心功能和电解质",
    additional_info: "需要利尿、抗凝和心律管理",
    created_at: new Date("2024-01-17"),
    updated_at: new Date("2024-01-17"),
  },
];

// Mock Medicines
const medicines: Medicine[] = [
  {
    _id: "med1",
    case_id: "case1",
    patient_id: "CVD001",
    medicine_name: "阿司匹林",
    dosage: "100mg",
    route: "oral",
    frequency: "每日一次",
    start_date: new Date("2024-01-15"),
    notes: "抗血小板聚集",
    created_at: new Date("2024-01-15"),
    updated_at: new Date("2024-01-15"),
  },
  {
    _id: "med2",
    case_id: "case1",
    patient_id: "CVD001",
    medicine_name: "阿托伐他汀",
    dosage: "20mg",
    route: "oral",
    frequency: "每晚一次",
    start_date: new Date("2024-01-15"),
    notes: "降脂治疗",
    created_at: new Date("2024-01-15"),
    updated_at: new Date("2024-01-15"),
  },
  {
    _id: "med3",
    case_id: "case2",
    patient_id: "CVD002",
    medicine_name: "氯吡格雷",
    dosage: "75mg",
    route: "oral",
    frequency: "每日一次",
    start_date: new Date("2024-01-16"),
    notes: "双重抗血小板治疗",
    created_at: new Date("2024-01-16"),
    updated_at: new Date("2024-01-16"),
  },
  {
    _id: "med4",
    case_id: "case3",
    patient_id: "CVD003",
    medicine_name: "呋塞米",
    dosage: "40mg",
    route: "oral",
    frequency: "每日两次",
    start_date: new Date("2024-01-17"),
    notes: "利尿消肿",
    created_at: new Date("2024-01-17"),
    updated_at: new Date("2024-01-17"),
  },
];

// Mock Treatments
const treatments: Treatment[] = [
  {
    _id: "treat1",
    case_id: "case1",
    patient_id: "CVD001",
    treatment_name: "生活方式干预",
    treatment_date: new Date("2024-01-15"),
    treatment_type: "lifestyle_change",
    outcome: "患者接受建议，开始戒烟和运动",
    notes: "低盐低脂饮食，适量运动，戒烟限酒",
    created_at: new Date("2024-01-15"),
    updated_at: new Date("2024-01-15"),
  },
  {
    _id: "treat2",
    case_id: "case2",
    patient_id: "CVD002",
    treatment_name: "经皮冠状动脉介入治疗(PCI)",
    treatment_date: new Date("2024-01-16"),
    treatment_type: "surgery",
    outcome: "手术成功，血流恢复正常",
    notes: "紧急PCI，植入药物洗脱支架",
    created_at: new Date("2024-01-16"),
    updated_at: new Date("2024-01-16"),
  },
  {
    _id: "treat3",
    case_id: "case3",
    patient_id: "CVD003",
    treatment_name: "心脏康复治疗",
    treatment_date: new Date("2024-01-17"),
    treatment_type: "therapy",
    outcome: "症状有所改善",
    notes: "包括运动训练、心理支持和教育",
    created_at: new Date("2024-01-17"),
    updated_at: new Date("2024-01-17"),
  },
];

// Combine into patients
export const mockPatients: Patient[] = [
  {
    demographics: demographics[0]!,
    vitals: [vitalSigns[0]!],
    historyPresentIllness: historyPresentIllness[0],
    pastMedicalHistory: undefined,
    medicationHistory: undefined,
    allergyHistory: undefined,
    cases: [cases[0]!],
    tests: [tests[0]!],
    medicines: [medicines[0]!, medicines[1]!],
    diagnoses: [diagnoses[0]!],
    treatments: [treatments[0]!],
  },
  {
    demographics: demographics[1]!,
    vitals: [vitalSigns[1]!],
    historyPresentIllness: historyPresentIllness[1],
    pastMedicalHistory: undefined,
    medicationHistory: undefined,
    allergyHistory: undefined,
    cases: [cases[1]!],
    tests: [tests[1]!],
    medicines: [medicines[2]!],
    diagnoses: [diagnoses[1]!],
    treatments: [treatments[1]!],
  },
  {
    demographics: demographics[2]!,
    vitals: [vitalSigns[2]!],
    historyPresentIllness: historyPresentIllness[2],
    pastMedicalHistory: undefined,
    medicationHistory: undefined,
    allergyHistory: undefined,
    cases: [cases[2]!],
    tests: [tests[2]!],
    medicines: [medicines[3]!],
    diagnoses: [diagnoses[2]!],
    treatments: [treatments[2]!],
  },
];

// Dashboard stats
export const dashboardStats = {
  totalPatients: 3,
  todayEncounters: 3,
  accuracy: 94.2,
  avgResponseTime: "2.3s",
  totalCases: 3,
  activeCases: 2,
  completedCases: 1,
};
